# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ ]

jobs:
  build:
    runs-on: mainserverJulian

    # strategy:
    #   matrix:
    #     node-version: [12.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      token_discord: ${{ secrets.TOKEN_DISCORD }}
      db_port: ${{ secrets.DB_PORT }}
      db_password: ${{ secrets.DB_PASSWORD }}
      db_password_root: ${{ secrets.DB_PASSWORD_ROOT }}

    steps:
      - uses: actions/checkout@v2

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: Update 3rd party docker containers
        run: docker-compose pull

      - name: Build app
        run: docker-compose build

      # - name: Spin up containers
      - name: Spin up containers
        run: docker-compose up -d
